substitutions:
  rotary_left_pin: "15" # sw5
  rotary_right_pin: "12" # sw3
  rotary_up_pin: "2" # sw4
  rotary_down_pin: "13" # sw2
  rotary_select_pin: "17" # sw1
  screen_left_pin: "GPIO0"
  screen_right_pin: "GPIO35"

binary_sensor:
  ## controls
  - platform: gpio
    pin:
      number: $screen_left_pin
      allow_other_uses: true
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
    internal: true
    on_press:
      then:
        media_player_group.select_next_player: media_group_component
  - platform: gpio
    pin:
      number: $screen_right_pin
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1
    internal: true
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
        homething_menu.option: homeThingMenu
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
        homething_menu.home: homeThingMenu
    - timing:
        - ON for at least 3s
      then:
      - lambda: |-
          id(sleep_toggle)->toggle();
  - platform: gpio
    internal: true
    pin:
      number: $rotary_left_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw5
    on_press:
      then:
        homething_menu.left: homeThingMenu
  - platform: gpio
    internal: true
    pin:
      number: $rotary_up_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw4
    on_press:
      then:
        homething_menu.up: homeThingMenu
  - platform: gpio
    internal: true
    pin:
      number: $rotary_right_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw3
    on_press:
      then:
        homething_menu.right: homeThingMenu
  - platform: gpio
    internal: true
    pin:
      number: $rotary_down_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw2
    on_press:
      then:
        homething_menu.down: homeThingMenu
  - platform: gpio
    internal: true
    pin:
      number: $rotary_select_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw1
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
        homething_menu.select: homeThingMenu
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
        homething_menu.option: homeThingMenu