substitutions:
  rotary_left_pin: "15"
  rotary_right_pin: "12"
  rotary_up_pin: "2"
  rotary_down_pin: "13"
  rotary_select_pin: "17"
  screen_left_pin: "GPIO0"
  screen_right_pin: "GPIO35"

binary_sensor:
  ## controls
  - platform: gpio
    pin:
      number: $screen_left_pin
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
    internal: true
    on_press:
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressScreenLeft();
    on_release:
      then:
      - lambda: |-
          id(homeThingMenu)->buttonReleaseScreenLeft();
  - platform: gpio
    pin:
      number: $screen_right_pin
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1
    internal: true
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressScreenRight();
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
      - lambda: |-
          id(homeThingMenu)->topMenu();
    - timing:
        - ON for at least 3s
      then:
      - lambda: |-
          id(sleep_toggle)->toggle();
  - platform: gpio
    internal: true
    pin:
      number: $rotary_left_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw5
    on_press:
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressLeft();
  - platform: gpio
    internal: true
    pin:
      number: $rotary_up_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw4
    on_press:
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressUp();
  - platform: gpio
    internal: true
    pin:
      number: $rotary_right_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw3
    on_press:
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressRight();
  - platform: gpio
    internal: true
    pin:
      number: $rotary_down_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw2
    on_press:
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressDown();
  - platform: gpio
    internal: true
    pin:
      number: $rotary_select_pin
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw1
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelect();
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelectHold();