binary_sensor:
  - platform: gpio
    id: M5_BtnA
    pin:
      number: 39
      inverted: true
    on_click:
      then:
        homething_menu.back: homeThingMenu
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
        homething_menu.select: homeThingMenu
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
        homething_menu.option: homeThingMenu
  - platform: gpio
    id: M5_BtnC
    pin:
      number: 37
      inverted: true
    on_click:
      then:
        homething_menu.right: homeThingMenu