# set up your name
esphome:
  name: "homething-lilygo"
  platform: ESP32
  board: featheresp32

# modify: device setup
substitutions:
  friendly_name: "homeThing example"

# menu configs: if you don't need a menu, remove it from here and in the homeThing config below

# switch menu
switch:
  # replace with your switchs
    - platform: homeassistant_switch_group
      entity_id: "switch.oven_fan"
      name: "Oven Fan"
      id: oven_fan_switch

homeassistant_switch_group:
  # defined above with switches
  id: switch_group_component
  switches:
    - id: "oven_fan_switch"

# sensor menu
text_sensor:
  - platform: homeassistant
    entity_id: "sensor.vancouver_forecast"
    name: "Weather"
    id: sensor_weather

homeassistant_sensor_group:
  id: sensor_group_component
  sensors:
    - id: sensor_weather

# light menu
light:
  - platform: homeassistant_light_group
    id: light_office_lamp
    entity_id: light.office_lamp
    name: Office Lamp

homeassistant_light_group:
  id: light_group_component
  lights:
    - id: light_office_lamp

# sonos favorite source
media_player_source_sonos:
  id: sonos

# media player menu
media_player:
  - platform: homeassistant_media_player
    name: Beam
    entity_id: "media_player.beam"
    id: media_player_beam
    type: speaker
    sources:
      - id: sonos
        type: sonos
  - platform: homeassistant_media_player
    name: TV
    entity_id: "media_player.55_tcl_roku_tv"
    id: media_player_tv
    type: roku
    soundbar:
      speaker: media_player_beam

homeassistant_media_player:
  id: media_group_component
  media_players:
    - id: media_player_beam
      type: speaker
    - id: media_player_tv
      type: roku

# service menu
homeassistant_service_group:
  id: service_group_component
  commands:
    - text: "desk nudge up"
      command:
        - lambda: |-
            ESP_LOGI("homeassistant_service_group", "nudge up");
        - homeassistant.service:
            service: button.press
            data:
              entity_id: "button.desk_position_nudge_up"

# homeThing config
# you only need one menu _group
homeThing:
  id: homeThingMenu
  sleep_switch: sleep_toggle #optional
  backlight: backlight #optional
  battery: #optional
    battery_percent: battery_percent
    charging: charging
   # need atleast 1 group_component
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display # required
  on_redraw: # required
    then:
      component.update: my_display
  display_state:
    draw_battery_level: true # only needed if you have a battery
    # probably leave these alone
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo

# maybe modify: display setup
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;

# maybe modify: include default ipod controls
packages:
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, 
      common/ipod/lilygo_tdisplay_ipod_backlight.yaml,
      common/ipod/lilygo_tdisplay_ipod_battery.yaml,
      common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml,
      common/ipod/lilygo_tdisplay_ipod_rotary.yaml,
      common/ipod/lilygo_tdisplay_ipod_sleep.yaml,
      common/fonts.yaml,
      common/icon_fonts.yaml
    ]
    refresh: 0s
    
# only remove components if you aren't using the group
external_components:
  - source:
      type: git
      url: https://github.com/landonr/homeThing
    refresh: 0s
    components: [homeThing]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
    refresh: 0s
    components: [ 
      homeassistant_component,
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_light_group,
      homeassistant_media_player,
      homeassistant_service_group,
      media_player_source,
      media_player_source_sonos
    ]

# don't need to modify past here
logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

ota:

api:
  id: homeassistant_api_id
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          id(homeThingMenu)->goToScreenFromString(screen_name);