esphome:
  name: fireremote
  platform: ESP32
  board: m5stack-fire

external_components:
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: main
    # refresh: 0s
      type: local
      path: components
    components: [homeThing]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
    refresh: 0s
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component, 
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_light_group,
      homeassistant_media_player,
      homeassistant_service_group,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]

packages:
  device_base: !include common/device_base.yaml
  setup: !include homeConfig/device_setup.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  menu_group: !include homeConfig/menu_group.yaml
  fonts: !include common/fonts.yaml
  icon_fonts: !include common/icon_fonts.yaml

substitutions:
  friendly_name: "homeThingFireRemote"
  large_heavy_font_size: "24"
  large_font_size: "24"
  medium_font_size: "20"
  small_font_size: "18"
  home_thing_logo_size: "64"
  material_font_large_size: "28"
  material_font_small_size: "24"

i2c:
  sda: 21
  scl: 22
  scan: True

ip5306:
  battery_level:
    name: ${friendly_name} Battery Percent
    id: battery_percent
    on_value :
      then:
        - lambda: |-
            ESP_LOGD("TEST", "Battery Percent");
            // if(id(battery_percent).state > previousBatteryLevel && !charging) {
            //     charging = true;
            // } else if(id(battery_percent).state <= previousBatteryLevel && charging) {
            //     charging = false;
            // }
            // previousBatteryLevel = id(battery_percent).state;
  charger_connected:
    internal: true
    id: connected
    on_press:
      then:
        - lambda: |-
            ESP_LOGD("TEST", "charging");
            // if (charging == false) {
            //   charging = true;
            // }
        
    on_release:
      then:
        - lambda: |-
            ESP_LOGD("TEST", "not charging");
            // if (charging == true) {
            //   charging = false;
            // }
  charge_full:
    id: full
    internal: true
    on_press:
      then:
        - lambda: ESP_LOGD("TEST", "fully charged");
    on_release:
      then:
        - lambda: ESP_LOGD("TEST", "still charging");

deep_sleep:
  id: deep_sleep_
  wakeup_pin: 39
  wakeup_pin_mode: INVERT_WAKEUP

binary_sensor:
  - platform: gpio
    id: M5_BtnA
    pin:
      number: 39
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollCounterClockwise(0);
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - lambda: |-
           id(homeThingMenu)->buttonPressSelect();
  - platform: gpio
    id: M5_BtnC
    pin:
      number: 37
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollClockwise(0);

# We can still control the backlight independently
switch:
  - platform: template
    name: ${friendly_name} Sleep Toggle
    id: sleep_toggle
    optimistic: true
    on_turn_on:
      then:
        - deep_sleep.enter:
            id: deep_sleep_

output:
  - platform: ledc
    pin: 32
    id: gpio_32_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO15
    num_leds: 10
    rgb_order: GRB
    id: side_light
    name: ${friendly_name} Remote Light"
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - addressable_rainbow:
          name: Rainbow Effect
          speed: 20
          width: 15

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

homeThing:
  id: homeThingMenu
  settings:
    mode: 3_button
  sleep_switch: sleep_toggle
  backlight: backlight
  battery:
    battery_percent: battery_percent
    charging: connected
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
    header_height: 24
    margin_size: 8
    slider_margin_size: 6
    scroll_bar_width: 8
    bottom_bar_margin: 8
    now_playing_max_lines: 5
    draw_now_playing_bottom_menu: true
    draw_battery_level: true
    dark_mode: true
    draw_volume_level: false
    draw_shuffle_disabled: false
    draw_header_time: true

display:
  - platform: ili9xxx
    model: M5STACK
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    id: my_display
    update_interval: 3600s 
    lambda: |-
      // manageLight();
      // if (idleTime < 0) {
      //   ESP_LOGD("drawing menu", "turning on");
      //   id(backlight).turn_on();
      //   idleTime = 0;
      // }
      id(homeThingMenu)->draw_menu_screen();
      return;
      
