esphome:
  name: "homething-lilygo"
  platform: ESP32
  board: featheresp32

external_components:
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: lando/codeCleanup
    # refresh: 0s
      type: local
      path: components
    components: [ 
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_light_group,
      homeassistant_media_player,
      homeassistant_service_group,
      homeThing,
    ]

packages:
  device_base: !include common/device_base.yaml
  ipod_control_backlight: !include common/ipod/lilygo_tdisplay_ipod_backlight.yaml
  ipod_control_battery: !include common/ipod/lilygo_tdisplay_ipod_battery.yaml
  ipod_control_binary_sensor: !include common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  ipod_control_rotary: !include common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  ipod_control_sleep: !include common/ipod/lilygo_tdisplay_ipod_sleep.yaml
  setup: !include homeConfig/device_setup.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  menu_group: !include homeConfig/menu_group.yaml
  fonts: !include common/fonts.yaml
  icon_fonts: !include common/icon_fonts.yaml

substitutions:
  friendly_name: "homeThingClear"

color:
  - id: my_red
    red_int: 197
    green_int: 43
    blue_int: 48
  - id: my_green
    red_int: 120
    green_int: 191
    blue_int: 26
  - id: my_blue
    red_int: 129
    green_int: 196
    blue_int: 255
  - id: my_yellow
    red_int: 255
    green_int: 204
    blue_int: 0
  - id: my_primary_accent
    red_int: 22
    green_int: 88
    blue_int: 142

homeThing:
  id: homeThingMenu
  settings:
    sleep_after: 14400
  sleep_switch: sleep_toggle
  backlight: backlight
  battery:
    battery_percent: battery_percent
    charging: charging
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    colors:
      accent_primary: my_primary_accent
      red: my_red
      green: my_green
      blue: my_blue
      yellow: my_yellow
    draw_battery_level: true
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
