esphome:
  name: m5stickc
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

esp32:
  board: m5stick-c
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

external_components:
  - source:
      type: git
      url: https://gitlab.com/geiseri/esphome_extras.git
    refresh: 0s
    components: [axp192]
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: main
    # refresh: 0s
      type: local
      path: components
    components: [homeThing]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
    refresh: 0s
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component, 
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_media_player,
      homeassistant_service_group,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]


packages:
  device_base: !include common/device_base.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  fonts: !include common/fonts.yaml
  icon_fonts: !include common/icon_fonts.yaml

substitutions:
  friendly_name: "homeThingM5StickC"

axp192:
 id: axp
 address: 0x34
 update_interval: 60s
 charge_voltage: 4150mV
 dcdc1_voltage: 3300mv
 dcdc3_voltage: 1.5V

sensor:
   # AXP192 power management - must be present to initialize TFT power on
 - platform: axp192
   axp192_id: axp
   id: batteryPercent
   type: battery_power

# internal LED
light:
 - platform: monochromatic
   output:  builtin_led
   name: Led
   id: led1
   internal: True
 - platform: monochromatic
   output: axp_ldo3
   restore_mode: ALWAYS_ON
   name: "Backlight"
   id: backlight
   internal: True

output:
 - platform: ledc
   pin: 10
   inverted: true
   id: builtin_led
 - platform: axp192
   axp192_id: axp
   output: ldo3
   id: axp_ldo3  

binary_sensor:
 - platform: axp192
   axp192_id: axp
   type: charge_indicate
   id: axp_charger
   name: "Charger"
   on_state:
     then:
       lambda: |-
        //  charging = x;
 - platform: gpio
   pin:
     number: GPIO37
     inverted: true
   name: Button A
   on_press:
     then:
       lambda: |-
           id(homeThingMenu)->buttonPressRight();
           auto call = id(led1).turn_on();
           call.set_transition_length(0);
           call.perform();
   on_release:
     then:
       - light.turn_off: led1
       
 - platform: gpio
   pin:
     number: GPIO39
     inverted: true
   name: Button B
   on_press:
     then:
       lambda: |-
           id(homeThingMenu)->buttonPressSelect();
           auto call = id(led1).turn_on();
           call.set_transition_length(0);
           call.perform();
   on_release:
     then:
       - light.turn_off: led1

deep_sleep:
 id: deep_sleep_
 wakeup_pin: 37
 wakeup_pin_mode: INVERT_WAKEUP

switch:
- platform: axp192
  axp192_id: axp
  output: ldo3
  name: LDO3
- platform: template
  id: sleep_toggle
  internal: true
  optimistic: true
  on_turn_on:
    then:
      - light.turn_off:
          id: backlight
          transition_length: 0s
      - delay: 0.5s
      - deep_sleep.enter:
          id: deep_sleep_

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

homeThing:
  id: homeThingMenu
  media_player_group: media_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  backlight: backlight
  on_redraw:
    then:
      component.update: my_display
  display_state:
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
    draw_now_playing_bottom_menu: True

display:
  - platform: st7735
    model: "INITR_18BLACKTAB"
    id: my_display
    reset_pin: GPIO18
    cs_pin: GPIO5
    dc_pin: GPIO23
    rotation: 90
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 3600s    
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
