esphome:
  name: tdisplayt4

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: main
    # refresh: 0s
      type: local
      path: components
    components: [homeThing]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
    refresh: 0s
      # type: local
      # path: ../local_components/components
    components: [
      homeassistant_component, 
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_light_group,
      homeassistant_media_player,
      homeassistant_service_group,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]

packages:
  device_base: !include common/device_base.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  menu_group: !include homeConfig/services.yaml
  fonts: !include common/fonts.yaml
  icon_fonts: !include common/icon_fonts.yaml

substitutions:
  friendly_name: "tdisplayT4"
  large_heavy_font_size: "24"
  large_font_size: "24"
  medium_font_size: "20"
  small_font_size: "18"
  home_thing_logo_size: "64"
  material_font_large_size: "28"
  material_font_small_size: "24"

sensor:
  - platform: rotary_encoder
    filters:
    - throttle: 0.01s
    name: "Rotary Encoder"
    internal: true
    pin_a:
      number: 26
      mode:
        input: true
        pullup: true
    pin_b:
      number: 33
      mode:
        input: true
        pullup: true
    id: rotary
    on_clockwise:
      - lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->rotaryScrollClockwise(id(rotary).state);
    on_anticlockwise:
      - lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->rotaryScrollCounterClockwise(id(rotary).state);
  - platform: template
    name: Battery Percent
    id: batteryPercent
    unit_of_measurement: '%'

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: 00
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw1
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelect();
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelectHold();
  - platform: gpio
    id: T4_BtnA
    pin:
      number: 39
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollCounterClockwise(0);
  - platform: gpio
    id: T4_BtnB
    pin:
      number: 37
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->buttonPressSelect();
  - platform: gpio
    id: T4_BtnC
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollClockwise(0);

switch:
  - platform: gpio
    pin:
      number: 27
      inverted: false
    id: comb
    internal: true
  - platform: gpio
    pin:
      number: 26
      inverted: false
    id: coma
    internal: true

spi:
  clk_pin: 18
  miso_pin: 12
  mosi_pin: 23

homeThing:
  id: homeThingMenu
  settings:
    mode: 3_button
    display_timeout: 0
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
    header_height: 24
    margin_size: 8
    slider_margin_size: 6
    scroll_bar_width: 8
    bottom_bar_margin: 8
    now_playing_max_lines: 10
    draw_now_playing_bottom_menu: true
    dark_mode: true
    draw_volume_level: false
    draw_header_time: true

display:
  - platform: ili9xxx
    id: my_display
    model: TFT_2.4
    cs_pin: 27
    dc_pin: 32
    reset_pin: 05
    update_interval: 3600s
    rotation: 270
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;