esphome:
  name: "white-homething"
  platform: ESP32
  board: featheresp32
  on_boot:
    priority: 600.0
    then:
      - delay: 45s
      - if:
          condition:
            not:
              - wifi.connected:
          then:
            - switch.turn_on: sleep_toggle

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wifi_id
  power_save_mode: HIGH
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_fallback_password

external_components:
  - source:
    #   type: git
    #   url: https://github.com/landonr/homeThing
    #   ref: main
    # refresh: 0s
      type: local
      path: components
    components: [homeThing]
  - source:
    #   type: git
    #   url: https://github.com/landonr/esphome-components
    #   ref: main
    # refresh: 0s
      type: local
      path: ../local_components/components
    components: [
      homeassistant_component, 
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_light_group,
      homeassistant_media_player,
      homeassistant_service_group,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]

packages:
  device_base: !include common/device_base.yaml
  ipod_control_backlight: !include common/ipod/lilygo_tdisplay_ipod_backlight.yaml
  ipod_control_battery: !include common/ipod/lilygo_tdisplay_ipod_battery.yaml
  ipod_control_binary_sensor: !include common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml
  ipod_control_rotary: !include common/ipod/lilygo_tdisplay_ipod_rotary.yaml
  ipod_control_sleep: !include common/ipod/lilygo_tdisplay_ipod_sleep.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  menu_group: !include homeConfig/services.yaml
  fonts: !include common/fonts.yaml
  icon_fonts: !include common/icon_fonts.yaml

substitutions:
  friendly_name: "white homething"

color:
  - id: my_primary_accent
    red_int: 75
    green_int: 45
    blue_int: 209

script:
  - id: feed_cat
    then:
      - homeassistant.service:
          service: button.press
          data:
            entity_id: "button.catfeeder_node_feed_single"

homeThing:
  id: homeThingMenu
  settings:
    sleep_after: 14400
  sleep_switch: sleep_toggle
  backlight: backlight
  battery:
    battery_percent: battery_percent
    charging: charging
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  # sensor_group: sensor_group_component
  # switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    colors:
      accent_primary: my_primary_accent
    draw_battery_level: true
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
  screens:
    name: settings
    switches:
      - id: "oven_fan_switch"
      - id: "restart_switch"
    text_sensors:
      - id: sensor_kitchen_air
      - id: sensor_temperature
    commands:
      - name: "desk nudge up"
        command:
          - lambda: |-
              ESP_LOGI("homeassistant_service_group", "nudge up");
          - homeassistant.service:
              service: button.press
              data:
                entity_id: "button.desk_position_nudge_up"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
