// https://gitlab.com/geiseri/esphome_extras/-/tree/main/components/axp192

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

axp192: # setup backlight and charging
  id: axp
  address: 0x34
  update_interval: 60s
  charge_voltage: 4150mV
  dcdc1_voltage: 3300mv
  dcdc3_voltage: 1.5V
  i2c_id: bus_a

sensor: # AXP192 power management - must be present to initialize TFT power on
 - platform: axp192
   axp192_id: axp
   id: batteryPercent
   type: battery_power

light: # internal LED
 - platform: monochromatic
   output:  builtin_led
   name: Led
   id: led1
   internal: True
 - platform: monochromatic
   output: axp_ldo2
   restore_mode: ALWAYS_ON
   name: "${friendly_name} Backlight"
   id: backlight

output:
 - platform: ledc
   pin: 10
   inverted: true
   id: builtin_led
 - platform: axp192
   axp192_id: axp
   output: ldo2
   id: axp_ldo2  

binary_sensor:
 - platform: axp192
   axp192_id: axp
   type: charge_indicate
   id: axp_charger
   name: "${friendly_name} Charging"
   on_state:
     then:
       lambda: |-
        //  charging = x;

switch:
- platform: axp192
  axp192_id: axp
  output: ldo3
  name: LDO3
