// https://github.com/martydingo/esphome-axp192

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

sensor:
  - platform: axp192
    model: M5STICKC
    id: axp_192
    address: 0x34
    i2c_id: bus_a
    update_interval: 1s
    brightness: 1.0
    charging:
      name: "${friendly_name} Charging"
      id: axp_charger
    battery_level:
      name: "${friendly_name} Battery Percent"
      id: batteryPercent
  
  # internal LED
light:
  - platform: monochromatic
    output:  builtin_led
    name: "${friendly_name} Led"
    id: led1
  - platform: monochromatic
    output: backlight_output
    restore_mode: ALWAYS_ON
    name: "${friendly_name} Backlight"
    id: backlight
  
output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led
  - platform: ledc
    pin: GPIO4
    id: gpio4
  - platform: template
    id: backlight_output
    type: float
    write_action:
      then:
        - lambda: |-
            ESP_LOGD("backlight", "Setting brightness to %f", state);
            if(id(backlight) == nullptr) return;
            auto light = id(backlight);
            auto light_on = light->remote_values.is_on() == true;
            ESP_LOGD("backlight", "Backlight %d, setting brightness to %f", light_on, state);
            if(light_on) {
              id(axp_192).set_brightness(state);
            } else {
              id(axp_192).set_brightness(0.0f);
            }
