binary_sensor:
 - platform: gpio
   pin:
     number: GPIO37
     inverted: true
   name: Button A
   on_press:
     then:
       lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->buttonPressSelect();
          id(led1).turn_on().set_transition_length(0).perform();
   on_release:
     then:
       - light.turn_off: led1
       
 - platform: gpio
   pin:
     number: GPIO39
     inverted: true
   name: Button B
   on_press:
     then:
       lambda: |-
        id(homeThingMenu)->buttonPressWakeUpDisplay();
        id(homeThingMenu)->topMenu(); 
        id(led1).turn_on().set_transition_length(0).perform();
   on_release:
     then:
       - light.turn_off: led1