captive_portal:

wifi:
  # update when flashing device

  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  # fast_connect: true

  # For out of box experience

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "homeThing Fallback Hotspot"

ota:
  platform: esphome

api:
  id: homeassistant_api_id
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          id(homeThingMenu)->goToScreenFromString(screen_name);
    - service: notify_homething
      variables:
        title: string
        message: string
        # type_str: string
      then:
        - lambda: |-
            id(homeThingMenu)->addNotification(title, message, "", true);

time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        component.update: my_display

binary_sensor:
  - platform: status
    id: api_connected
    internal: true

sensor:
  # Uptime sensor.
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 10s