logger:
  level: INFO

ota:

api:
  id: homeassistant_api_id
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          id(homeThingMenu)->goToScreenFromString(screen_name);

http_request:
  useragent: esphome/device
  timeout: 10s

time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        component.update: my_display

binary_sensor:
  - platform: status
    id: api_connected
    internal: true

sensor:
  # Uptime sensor.
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 10s
  - platform: template
    name: "${friendly_name} Free Memory"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    unit_of_measurement: 'B'
    state_class: measurement
    update_interval: 10s
    
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    internal: True
    
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    id: wifi_signal_percent
    internal: True
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      internal: True
      id: wifi_ip
    ssid:
      name: SSID
      internal: True
      id: wifi_ssid