logger:
  level: INFO

ota:

api:
  id: homeassistant_api_id
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          id(homeThingMenu)->goToScreenFromString(screen_name);

http_request:
  useragent: esphome/device
  timeout: 10s

time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        component.update: my_display

binary_sensor:
  - platform: status
    id: api_connected
    internal: true

sensor:
  # Uptime sensor.
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 1s
  - platform: template
    name: "${friendly_name} Free Memory"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    unit_of_measurement: 'B'
    state_class: measurement
    update_interval: 1s