logger:
  level: WARN

ota:

api:
  id: homeassistant_api_id
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          id(homeThingMenu)->goToScreenFromString(screen_name);

time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      then:
        component.update: my_display

binary_sensor:
  - platform: status
    id: api_connected
    internal: true

sensor:
  # Uptime sensor.
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 10s