substitutions:
  launch_image_file: "https://github.com/landonr/homeThing/raw/main/docs/homeThingLogoWhite.svg"
  launch_image_size: "48x48"
  launch_image_type: "TRANSPARENT_BINARY"
  weather_icon_size: "50x50"

image:
  - id: launch_image
    file: $launch_image_file
    resize: $launch_image_size
    type: $launch_image_type
  - file: mdi:weather-night
    id: weather_clear
    resize: $weather_icon_size
  - file: mdi:weather-cloudy
    id: weather_cloudy
    resize: $weather_icon_size
  - file: mdi:weather-fog
    id: weather_fog
    resize: $weather_icon_size
  - file: mdi:weather-hail
    id: weather_hail
    resize: $weather_icon_size
  - file: mdi:weather-rainy
    id: weather_rainy
    resize: $weather_icon_size
  - file: mdi:weather-snowy
    id: weather_snow
    resize: $weather_icon_size
  - file: mdi:weather-sunny
    id: weather_sunny
    resize: $weather_icon_size
  - file: mdi:weather-windy
    id: weather_windy
    resize: $weather_icon_size

sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: weather.accuweather
    attribute: temperature
  - platform: homeassistant
    id: weather_humidity
    entity_id: weather.accuweather
    attribute: humidity

text_sensor:
  - platform: homeassistant
    entity_id: "sensor.weather_condition"
    name: "Weather state"
    id: weather_state
