substitutions:
  mic_lrclk_pin: "3"
  mic_bclk_pin: "2"
  mic_din_pin: "1"

i2s_audio:
  i2s_lrclk_pin: $mic_lrclk_pin # WS
  i2s_bclk_pin: $mic_bclk_pin # SCK

microphone:
  - platform: i2s_audio
    id: external_mic
    i2s_din_pin: $mic_din_pin # SD
    adc_type: external
    pdm: false
    channel: left

voice_assistant:
  microphone: external_mic
  on_start:
    then:
      - homething_menu.clear_notifications: homeThingMenu
      - homething_menu.add_notification: homeThingMenu
          title: "Voice Assistant"
          message: "Listening"
          icon: ""
          persistent: false
  on_error:
    then:
      - homething_menu.add_notification: homeThingMenu
          title: "Voice Assistant"
          subtitle: "Error"
          message: x
          persistent: true
  on_stt_end:
    then:
      - homething_menu.add_notification: homeThingMenu
          title: "Voice Assistant"
          subtitle: "Understood"
          message: x
          persistent: true
  on_tts_start:
    then:
      - homething_menu.add_notification: homeThingMenu
          title: "Voice Assistant"
          subtitle: "Speaking"
          message: x
          persistent: false
